### ISSUE TITLE
mkdir: cannot create directory 'log': File exists

### ISSUE THREAD

**Issue by marketavlkova** [slt666666/NLRtracker#13]
When trying to run the NLRtracker.sh script for the first time I've got stuck at the first command:

```
# log
if [ ! -f log ]; then
  mkdir log
fi
```

with an error message:
`mkdir: cannot create directory ‘log’: File exists`

I believe the part above should be changed to:

```
# log
if [ ! -d log ]; then
  mkdir log
fi
```

**Comment by slt666666** [comment]
Thank you for pointing this out!
We'll fix it as soon as possible.

Best,
Toshi
