### ISSUE TITLE
Parsing fasta headers

### ISSUE THREAD

**Issue by dence** [slt666666/NLRtracker#2]
Hi, I've been working on running NLRtracker on several denovo RNAseq assemblies and found that the fasta outputs from NLRtracker were empty. This was because the input fasta files had long headers that were delimited by a space not a tab. I fixed this on line 365 of the NLRtracker.R script. Since it is only one line, I figured I would just post it here rather than do a pull request and merge. 

Thank you for the tool! I hope your classification schema helps standardize NLR discussions in the future. 

Thanks,
Daniel

**Comment by slt666666** [comment]
Hi Daniel,
Thank you for your comment!
We'll fix some parts.

Thanks,
Toshi
