### ISSUE TITLE
Can NLRtracker use as input file contigs obtained from RenSeq?

### ISSUE THREAD

**Issue by cahuparo** [slt666666/NLRtracker#3]
Hi! 

First! Thanks for putting together NLRtracker and for making it available. I am using renseq to capture and sequence NLRs in Sweetpotato. I am wondering if NLR tracker could handle as input file the contigs obtained from a RenSeq run. How would it handle multiple NLRs within a single contig? 

Any suggestions would be greatly appreciated. 

Best, 

Camilo

**Comment by slt666666** [comment]
Hi, Sorry for the late reply. And thank you for your comments.

Unfortunately, NLRtracker works on gene-level sequences.
So, if a contig has multiple NLRs, the NLRtracker will annotate it as one NLR (ex "contigA" is NLR).

NLRtracker might be applicable after gene annotation to contigs/scaffolds...etc.

Best,
Toshi

**Comment by cahuparo** [comment]
Hi Toshi, 

That makes sense. I am wondering if it can be a good tool to filter contigs that have NLRs before generating gene models. I want to calculate the capture rate from renseq output. I am also working on generating gene models so I will definitely give it a try in the near future. 

Thanks,

Camilo
