### ISSUE TITLE
FIMO failed

### ISSUE THREAD

**Issue by sadikmu** [slt666666/NLRtracker#5]
Hi Running NLRtracker on the test data failed at FIMO state. Trie to replace the provided meme.xml with NLR-annotator one but failed with the same error. Install FIMO is v4.12.0.

Any suggestion on what I've missed getting it run successfully?

```
fimo -o out_dir/fimo_out module/meme.xml sample_data/sample.fasta
Errors from MEME XML parser:
Expected state IN_USE_LLR not found!
FATAL: No motifs could be read.
```

**Comment by slt666666** [comment]
Hi, I modified some file paths in scripts.
And FIMO version 4.XXX and 5.XXX are very different (input/output format...etc)
So, I recommend using FIMO version 5.2.0 instead of v4.12.0 for NLRtracker.
Thanks.

**Comment by sadikmu** [comment]
Thanks, I used v5.2.3 and it's working perfectly. One additional point though on the fimo.gff parsing R script: Could you please clarify the source of annotation signature assigned to describe Motif 1 -20 ?  For example "Motif 1" annotated to "P-loop" type - is there a way to double-check this? database or motif list their descriptions or any other?

**Comment by slt666666** [comment]
Sounds good!
You can check Motif information from NLR-Annotator paper: https://doi.org/10.1104/pp.19.01273
or our source code: module/NLRtracker.R (line 93~)
