### ISSUE TITLE
About version

### ISSUE THREAD

**Issue by Lsz-20** [slt666666/NLRtracker#7]
Thanks for your offer
But it seems some thing wrong?
i'm using conda to install the packages,as your advice: interproscan=5.53 & meme=5.2,but it can't be found in anaconda.org.
so if i use interproscan=5.54 & meme=5.4.1 ,will there be any mistakes?
Here are some errors when i running:
——————————interproscan=5.54 & hmmer=3.3.2 & r-base=4.1.2 & meme=4.11————————
Run NLRtracker
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.7
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Error in `stop_subscript()`:
! Can't rename columns that don't exist.
✖ Column `V2` doesn't exist.
Backtrace:

![image](https://user-images.githubusercontent.com/60343452/153005379-b57ec619-5afb-4712-93c0-fb9c9ce9ef4d.png)

Thanks for your reply

**Comment by slt666666** [comment]
Hi,
The output format of MEME is different across MEME versions.
I guess interproscan=5.54 is not a problem.
Your log showed (——————————interproscan=5.54 & hmmer=3.3.2 & r-base=4.1.2 & **meme=4.11**————————).
You might use meme=4.11, could you try again with meme=5.2?

**Comment by Lsz-20** [comment]
> Hi, The output format of MEME is different across MEME versions. I guess interproscan=5.54 is not a problem. Your log showed (——————————interproscan=5.54 & hmmer=3.3.2 & r-base=4.1.2 & **meme=4.11**————————). You might use meme=4.11, could you try again with meme=5.2?

Thanks for your apply.and I have tried the versions like this:interproscan=5.54 & hmmer=3.3.2 & r-base=4.1.0 & **meme=5.4.1 & 5.3.0 but it show me the same quesiton...
because i install meme with bioconda, and can't find 5.2.0,it only show me:5.4.1 5.3.0 5.1.1....

**Comment by slt666666** [comment]
I see...
Could you show me all logs? (from --------------------- input & option -----------------------)

**Comment by Lsz-20** [comment]
here are the -err.log in log:
---------------------- input & option -----------------------
Fasta file             = Physo3_246483_328.fasta
output directory       = outs

---------------------- input & option -----------------------

Run Interproscan
InterProScan version 5.54-87.0
InterProScan 64-Bit build  (requires Java 11)

interproscan.sh -i outs/tmp.fasta -f gff3 -t p -o outs/interpro_result.gff -cpu 2 -appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles
09/02/2022 02:03:02:197 Welcome to InterProScan-5.54-87.0
09/02/2022 02:03:02:198 Running InterProScan v5 in STANDALONE mode... on Linux
09/02/2022 02:03:07:218 RunID: 926a67f1c5b6_20220209_020307093_bpvo
09/02/2022 02:03:15:651 Loading file /nfs/my/lsz/NLR/NLRtracker-master/outs/tmp.fasta
09/02/2022 02:03:15:653 Running the following analyses:
[CDD-3.18,Gene3D-4.3.0,Pfam-34.0,PRINTS-42.0,ProSiteProfiles-2021_01,SMART-7.1,SUPERFAMILY-1.75]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
09/02/2022 02:03:26:243 26% completed
09/02/2022 02:03:46:289 52% completed
09/02/2022 02:03:52:570 76% completed
09/02/2022 02:04:02:661 91% completed
09/02/2022 02:04:07:355 100% done:  InterProScan analyses completed 

2022-02-09 02:04:07,861 [main] [uk.ac.ebi.interpro.scan.jms.main.Run:1883] WARN - deleteWorkingDirectoryOnCompletion : false

Run FIMO

fimo -o outs/fimo_out ./module/meme.xml outs/tmp.fasta
Using motif 1 of width 21.
Computing q-values.
Using motif 2 of width 29.
Computing q-values.
Using motif 3 of width 21.
Computing q-values.
Using motif 4 of width 15.
Computing q-values.
Using motif 5 of width 20.
Computing q-values.
Using motif 6 of width 29.
Computing q-values.
Using motif 7 of width 21.
Computing q-values.
Using motif 8 of width 21.
Computing q-values.
Using motif 9 of width 21.
Computing q-values.
Using motif 10 of width 15.
Computing q-values.
Using motif 11 of width 19.
Computing q-values.
Using motif 12 of width 15.
Computing q-values.
Using motif 13 of width 32.
Computing q-values.
Using motif 14 of width 50.
Computing q-values.
Using motif 15 of width 21.
Computing q-values.
Using motif 16 of width 17.
Computing q-values.
Using motif 17 of width 36.
Computing q-values.
Using motif 18 of width 33.
Computing q-values.
Using motif 19 of width 41.
Computing q-values.
Using motif 20 of width 50.
Computing q-values.

Run HMMER

hmmsearch --domtblout outs/CJID.txt ./module/abe3069_Data_S1.hmm outs/tmp.fasta
# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  ./module/abe3069_Data_S1.hmm
# target sequence database:        outs/tmp.fasta
# per-dom hits tabular output:     outs/CJID.txt
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       alignedSeq_for_hmm_jelly2  [M=116]
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence Description
    ------- ------ -----    ------- ------ -----   ---- --  -------- -----------

   [No hits detected that satisfy reporting thresholds]


Domain annotation for each sequence (and alignments):

   [No targets detected that satisfy reporting thresholds]


Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (116 nodes)
Target sequences:                          1  (328 residues searched)
Passed MSV filter:                         0  (0); expected 0.0 (0.02)
Passed bias filter:                        0  (0); expected 0.0 (0.02)
Passed Vit filter:                         0  (0); expected 0.0 (0.001)
Passed Fwd filter:                         0  (0); expected 0.0 (1e-05)
Initial search space (Z):                  1  [actual number of targets]
Domain search space  (domZ):               0  [number of targets reported over threshold]
# CPU time: 0.00u 0.00s 00:00:00.00 Elapsed: 00:00:00.00
# Mc/sec: 6.34
//
[ok]

Run NLRtracker
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Warning messages:
1: package ‘tibble’ was built under R version 4.1.1 
2: package ‘tidyr’ was built under R version 4.1.2 
3: package ‘readr’ was built under R version 4.1.2 
Error in `stop_subscript()`:
! Can't rename columns that don't exist.
✖ Column `V2` doesn't exist.
Backtrace:
     ▆
  1. ├─... %>% ...
  2. ├─dplyr::mutate(...)
  3. ├─dplyr::left_join(., InterProScan, by = "ENTRY_AC")
  4. ├─dplyr::mutate(...)
  5. ├─dplyr::filter(...)
  6. ├─dplyr::rename(...)
  7. └─dplyr:::rename.data.frame(...)
  8.   └─tidyselect::eval_rename(expr(c(...)), .data)
  9.     └─tidyselect:::rename_impl(...)
 10.       └─tidyselect:::eval_select_impl(...)
 11.         ├─tidyselect:::with_subscript_errors(...)
 12.         │ ├─base::tryCatch(...)
 13.         │ │ └─base tryCatchList(expr, classes, parentenv, handlers)
 14.         │ │   └─base tryCatchOne(expr, names, parentenv, handlers[[1L]])
 15.         │ │     └─base doTryCatch(return(expr), name, parentenv, handler)
 16.         │ └─tidyselect:::instrument_base_errors(expr)
 17.         │   └─base::withCallingHandlers(...)
 18.         └─tidyselect:::vars_select_eval(...)
 19.           └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 20.             └─tidyselect:::eval_c(expr, data_mask, context_mask)
 21.               └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 22.                 └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 23.                   └─tidyselect:::as_indices_sel_impl(...)
 24.                     └─tidyselect:::as_indices_impl(x, vars, strict = strict)
 25.                       └─tidyselect:::chr_as_locations(x, vars)
 26.                         └─vctrs::vec_as_location(x, n = length(vars), names = vars)
 27.                           └─vctrs `<fn>`()
 28.                             └─vctrs:::stop_subscript_oob(...)
 29.                               └─vctrs:::stop_subscript(...)
 30.                                 └─rlang::abort(...)
Execution halted

Finish NLRtracker!

**Comment by slt666666** [comment]
Thanks! the other part looks ok.
Have you tried with meme=5.1.1??

**Comment by Lsz-20** [comment]
> Thanks! the other part looks ok. Have you tried with meme=5.1.1??

I have tried meme=5.2.0,and it show me the same problem,perhaps any advice?:
---------------------- input & option -----------------------
Fasta file             = Physo3_246483_328.fasta
output directory       = outs

---------------------- input & option -----------------------

Run Interproscan
InterProScan version 5.54-87.0
InterProScan 64-Bit build  (requires Java 11)

interproscan.sh -i outs/tmp.fasta -f gff3 -t p -o outs/interpro_result.gff -cpu 2 -appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles
10/02/2022 03:27:45:737 Welcome to InterProScan-5.54-87.0
10/02/2022 03:27:45:738 Running InterProScan v5 in STANDALONE mode... on Linux
10/02/2022 03:27:50:905 RunID: 926a67f1c5b6_20220210_032750787_byx7
10/02/2022 03:27:59:327 Loading file /nfs/my/lsz/NLR/NLRtracker-master/outs/tmp.fasta
10/02/2022 03:27:59:328 Running the following analyses:
[CDD-3.18,Gene3D-4.3.0,Pfam-34.0,PRINTS-42.0,ProSiteProfiles-2021_01,SMART-7.1,SUPERFAMILY-1.75]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
10/02/2022 03:28:10:235 28% completed
10/02/2022 03:28:31:609 54% completed
10/02/2022 03:28:40:525 78% completed
10/02/2022 03:28:42:861 93% completed
10/02/2022 03:28:47:351 100% done:  InterProScan analyses completed 

2022-02-10 03:28:47,855 [main] [uk.ac.ebi.interpro.scan.jms.main.Run:1883] WARN - deleteWorkingDirectoryOnCompletion : false

Run FIMO

fimo -o outs/fimo_out ./module/meme.xml outs/tmp.fasta
Using motif 1 of width 21.
Computing q-values.
Using motif 2 of width 29.
Computing q-values.
Using motif 3 of width 21.
Computing q-values.
Using motif 4 of width 15.
Computing q-values.
Using motif 5 of width 20.
Computing q-values.
Using motif 6 of width 29.
Computing q-values.
Using motif 7 of width 21.
Computing q-values.
Using motif 8 of width 21.
Computing q-values.
Using motif 9 of width 21.
Computing q-values.
Using motif 10 of width 15.
Computing q-values.
Using motif 11 of width 19.
Computing q-values.
Using motif 12 of width 15.
Computing q-values.
Using motif 13 of width 32.
Computing q-values.
Using motif 14 of width 50.
Computing q-values.
Using motif 15 of width 21.
Computing q-values.
Using motif 16 of width 17.
Computing q-values.
Using motif 17 of width 36.
Computing q-values.
Using motif 18 of width 33.
Computing q-values.
Using motif 19 of width 41.
Computing q-values.
Using motif 20 of width 50.
Computing q-values.

Run HMMER

hmmsearch --domtblout outs/CJID.txt ./module/abe3069_Data_S1.hmm outs/tmp.fasta
# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  ./module/abe3069_Data_S1.hmm
# target sequence database:        outs/tmp.fasta
# per-dom hits tabular output:     outs/CJID.txt
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       alignedSeq_for_hmm_jelly2  [M=116]
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence Description
    ------- ------ -----    ------- ------ -----   ---- --  -------- -----------

   [No hits detected that satisfy reporting thresholds]


Domain annotation for each sequence (and alignments):

   [No targets detected that satisfy reporting thresholds]


Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (116 nodes)
Target sequences:                          1  (328 residues searched)
Passed MSV filter:                         0  (0); expected 0.0 (0.02)
Passed bias filter:                        0  (0); expected 0.0 (0.02)
Passed Vit filter:                         0  (0); expected 0.0 (0.001)
Passed Fwd filter:                         0  (0); expected 0.0 (1e-05)
Initial search space (Z):                  1  [actual number of targets]
Domain search space  (domZ):               0  [number of targets reported over threshold]
# CPU time: 0.00u 0.00s 00:00:00.00 Elapsed: 00:00:00.00
# Mc/sec: 58.94
//
[ok]

Run NLRtracker
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Warning messages:
1: package ‘tibble’ was built under R version 4.1.1 
2: package ‘tidyr’ was built under R version 4.1.2 
3: package ‘readr’ was built under R version 4.1.2 
Error in `stop_subscript()`:
! Can't rename columns that don't exist.
✖ Column `V2` doesn't exist.
Backtrace:
     ▆
  1. ├─... %>% ...
  2. ├─dplyr::mutate(...)
  3. ├─dplyr::left_join(., InterProScan, by = "ENTRY_AC")
  4. ├─dplyr::mutate(...)
  5. ├─dplyr::filter(...)
  6. ├─dplyr::rename(...)
  7. └─dplyr:::rename.data.frame(...)
  8.   └─tidyselect::eval_rename(expr(c(...)), .data)
  9.     └─tidyselect:::rename_impl(...)
 10.       └─tidyselect:::eval_select_impl(...)
 11.         ├─tidyselect:::with_subscript_errors(...)
 12.         │ ├─base::tryCatch(...)
 13.         │ │ └─base tryCatchList(expr, classes, parentenv, handlers)
 14.         │ │   └─base tryCatchOne(expr, names, parentenv, handlers[[1L]])
 15.         │ │     └─base doTryCatch(return(expr), name, parentenv, handler)
 16.         │ └─tidyselect:::instrument_base_errors(expr)
 17.         │   └─base::withCallingHandlers(...)
 18.         └─tidyselect:::vars_select_eval(...)
 19.           └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 20.             └─tidyselect:::eval_c(expr, data_mask, context_mask)
 21.               └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 22.                 └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 23.                   └─tidyselect:::as_indices_sel_impl(...)
 24.                     └─tidyselect:::as_indices_impl(x, vars, strict = strict)
 25.                       └─tidyselect:::chr_as_locations(x, vars)
 26.                         └─vctrs::vec_as_location(x, n = length(vars), names = vars)
 27.                           └─vctrs `<fn>`()
 28.                             └─vctrs:::stop_subscript_oob(...)
 29.                               └─vctrs:::stop_subscript(...)
 30.                                 └─rlang::abort(...)
Execution halted

**Comment by slt666666** [comment]
I might understand the problem. I guess if you try sample fasta file (in this repository), NLRtracker will work.
maybe if fimo output is empty (no motif matching), the error has occurred.
I'll modify this problem soon, but it will take some time.
So, if you want to run NLRtracker with your fasta file, please add an NLR sequence to your fasta file.
(ex) ZAR1,
>AtZAR1
MVDAVVTVFLEKTLNILEEKGRTVSDYRKQLEDLQSELKYMQSFLKDAERQKRTNETLRTLVADLRELVYEAEDILVDCQLADGDDGNEQRSSNAWLSRLHPARVPLQYKKSKRLQEINERITKIKSQVEPYFEFITPSNVGRDNGTDRWSSPVYDHTQVVGLEGDKRKIKEWLFRSNDSQLLIMAFVGMGGLGKTTIAQEVFNDKEIEHRFERRIWVSVSQTFTEEQIMRSILRNLGDASVGDDIGTLLRKIQQYLLGKRYLIVMDDVWDKNLSWWDKIYQGLPRGQGGSVIVTTRSESVAKRVQARDDKTHRPELLSPDNSWLLFCNVAFAANDGTCERPELEDVGKEIVTKCKGLPLTIKAVGGLLLCKDHVYHEWRRIAEHFQDELRGNTSETDNVMSSLQLSYDELPSHLKSCILTLSLYPEDCVIPKQQLVHGWIGEGFVMWRNGRSATESGEDCFSGLTNRCLIEVVDKTYSGTIITCKIHDMVRDLVIDIAKKDSFSNPEGLNCRHLGISGNFDEKQIKVNHKLRGVVSTTKTGEVNKLNSDLAKKFTDCKYLRVLDISKSIFDAPLSEILDEIASLQHLACLSLSNTHPLIQFPRSMEDLHNLQILDASYCQNLKQLQPCIVLFKKLLVLDMTNCGSLECFPKGIGSLVKLEVLLGFKPARSNNGCKLSEVKNLTNLRKLGLSLTRGDQIEEEELDSLINLSKLMSISINCYDSYGDDLITKIDALTPPHQLHELSLQFYPGKSSPSWLSPHKLPMLRYMSICSGNLVKMQEPFWGNENTHWRIEGLMLSSLSDLDMDWEVLQQSMPYLRTVTANWCPELESFAIEDVGFRGGVWMKTPLHRT)

**Comment by Lsz-20** [comment]
As your advice, the sample.fasta can run well,and i also tried these two  methods：
（1）adding my fasta after sample.fasta,it can work
（2）adding ZAR1 you show above before my fasta,it can't work?

**Comment by Lsz-20** [comment]
Sorry to disturb  once again.I have tried to make some modifications,but some errors still exist.(with my fasta without any additional content)
(1) in NLRtracker.sh, the interproscan with "-appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles" I have deleted. And it can't work well.
(2) I think there may be some thing wrong in model/abe3069_Data_S1.hmm & meme.xml. May you perhaps tell you how the two documents were obtained?It seems to be the hmmer stage because no conforming content was found, the output without scores is shown in the figure below:
![image](https://user-images.githubusercontent.com/60343452/153368614-6f680612-61e4-4275-bfd2-dac9cd6beec4.png)

Looking forward to your reply!

**Comment by slt666666** [comment]
Sorry for the late response.
(1) "-appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles"
-> we use only these DB information in NLRtracker. So, NLRtracker requires this option.

(2) It's not the problem. The result just showed "Any motifs (in abe3069_Data_S1.hmm) didn't match your input fasta file."
If your fasta file contains several NLRs or if you use sample fasta file, some motifs might match.

As I commented before, I have to modify the case when there is no motif matching.
So, I thought the current best way is ...
1. use your fasta + sample.fasta as input
2. run NLRtracker.
3. then, remove NLRs of sample.fasta.

**Comment by Lsz-20** [comment]
> Sorry for the late response. (1) "-appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles" -> we use only these DB information in NLRtracker. So, NLRtracker requires this option.
> 
> (2) It's not the problem. The result just showed "Any motifs (in abe3069_Data_S1.hmm) didn't match your input fasta file." If your fasta file contains several NLRs or if you use sample fasta file, some motifs might match.
> 
> As I commented before, I have to modify the case when there is no motif matching. So, I thought the current best way is ...
> 
> 1. use your fasta + sample.fasta as input
> 2. run NLRtracker.
> 3. then, remove NLRs of sample.fasta.

OK，Thanks for your detailed reply！
