### ISSUE TITLE
Is it possible to run on assembled genome file

### ISSUE THREAD

**Issue by Saadserfraz** [slt666666/NLRtracker#8]
Hi,

When I run NLR_tracker on the assembled genome, the following error occurs each time.  It may be because hmmscan can not be performed on nucleotide files. Please explain if it's still possible to run a complete annotation pipeline on genome files.

Warning messages:
1: In min(start) : no non-missing arguments to min; returning Inf
2: In max(end) : no non-missing arguments to max; returning -Inf
Warning message:
Problem with `mutate()` column `Domain`.
ℹ `Domain = case_when(...)`.
ℹ NAs introduced
[slurm-21286630.log](https://github.com/slt666666/NLRtracker/files/8091017/slurm-21286630.log)
 by coercion
Error in file(file, "rt") : invalid 'description' argument
Calls: %>% ... list2 -> rename -> read.delim -> read.table -> file
Execution halted

**Comment by slt666666** [comment]
Hi, thank you for your comment.
Unfortunately, as we described in README, NLRtracker extracts and functionally annotates NLRs from protein or transcript files.
NLRtracker is not suitable for genome sequence files.
We recommend NLR Annotator(https://github.com/steuernb/NLR-Annotator) is one option to annotate NLRs in large sequences.
