### ISSUE TITLE
empty outputs

### ISSUE THREAD

**Issue by Lsz-20** [slt666666/NLRtracker#9]
Thanks for your code.
It seems that there are some problems with the output results:
the NLR.lst NLR.fasta NLR.gff3 NBARC.fasta and NBARC_deduplictated.fasta i got are empty and the NLRtracker.tsv shows me this.
![image](https://user-images.githubusercontent.com/60343452/155735891-ebf3a867-4d1a-4b52-a9fb-db0824e170bf.png)

and then i try the command with -i sample_data/test_interpro.gff3 -f sample_data/test_fimo.gff shich are offered in sample_data and all work well.
so i try to test my InterProScan & FIMO,the result shows that there has trouble in InterProScan,the output .gff3 is different from sample_data/test_interpro.gff3,with command: ./interproscan.sh -i ./sample_data/sample.fasta -f gff3  -o ./interpro_result.gff -appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles -dp
the version is 5.54_87.0.Here are the results after InterProScan
============
##gff-version 3
##feature-ontology http://song.cvs.sourceforge.net/viewvc/song/ontology/sofa.obo?revision=1.269
##interproscan-version 5.54-87.0
##sequence-region NP_001325023 1 648
NP_001325023	.	polypeptide	1	648	.	+	.	ID=NP_001325023;md5=4a8b389e0adecef09333d5e5ae1fced9
NP_001325023	SMART	protein_match	100	293	8.8E-13	+	.	date=25-02-2022;Target=NP_001325023 100 293;ID=match$1_100_293;Name=SM00382;status=T;Dbxref="InterPro:IPR003593"
##sequence-region NP_001330213 1 915
NP_001330213	.	polypeptide	1	915	.	+	.	ID=NP_001330213;md5=9e2aca43a60aa673bedf6b82d9157b65
NP_001330213	Pfam	protein_match	396	495	3.2E-11	+	.	date=25-02-2022;Target=NP_001330213 396 495;ID=match$2_396_495;signature_desc=ATPase family associated with various cellular activities (AAA);Name=PF00004;status=T;Dbxref="InterPro:IPR003959"
NP_001330213	SMART	protein_match	392	530	1.2E-7	+	.	date=25-02-2022;Target=NP_001330213 392 530;ID=match$3_392_530;Name=SM00382;status=T;Dbxref="InterPro:IPR003593"
NP_001330213	CDD	protein_match	389	492	2.29809E-12	+	.	date=25-02-2022;Target=NP_001330213 389 492;ID=match$4_389_492;signature_desc=AAA;Name=cd00009;status=T
##sequence-region Solyc09g092410.3.1 1 1051
Solyc09g092410.3.1	.	polypeptide	1	1051	.	+	.	ID=Solyc09g092410.3.1;md5=86e53abb2992cd8ad830b6e64dd6d9a8
Solyc09g092410.3.1	SMART	protein_match	195	333	3.8E-4	+	.	date=25-02-2022;Target=Solyc09g092410.3.1 195 333;ID=match$5_195_333;Name=SM00382;status=T;Dbxref="InterPro:IPR003593"
##sequence-region NP_001329653 1 1820
NP_001329653	.	polypeptide	1	1820	.	+	.	ID=NP_001329653;md5=b830d9bfb261333e804dbe22e3108b88
NP_001329653	CDD	protein_match	750	927	8.62729E-9	+	.	date=25-02-2022;Target=NP_001329653 750 927;ID=match$6_750_927;signature_desc=AAA;Name=cd00009;status=T
##sequence-region Solyc09g092280.1.1 1 846
Solyc09g092280.1.1	.	polypeptide	1	846	.	+	.	ID=Solyc09g092280.1.1;md5=2e185e7f6fd4beb0575c8028b71816ab
Solyc09g092280.1.1	CDD	protein_match	185	296	6.5345E-7	+	.	date=25-02-2022;Target=Solyc09g092280.1.1 185 296;ID=match$7_185_296;signature_desc=AAA;Name=cd00009;status=T
Solyc09g092280.1.1	SMART	protein_match	179	327	9.8E-6	+	.	date=25-02-2022;Target=Solyc09g092280.1.1 179 327;ID=match$8_179_327;Name=SM00382;status=T;Dbxref="InterPro:IPR003593"
##sequence-region Solyc09g092310.1.1 1 850
Solyc09g092310.1.1	.	polypeptide	1	850	.	+	.	ID=Solyc09g092310.1.1;md5=8675122f855549fd827e65cf59088577
Solyc09g092310.1.1	SMART	protein_match	178	312	5.9E-4	+	.	date=25-02-2022;Target=Solyc09g092310.1.1 178 312;ID=match$9_178_312;Name=SM00382;status=T;Dbxref="InterPro:IPR003593"
##sequence-region Solyc09g092290.1.1 1 848
Solyc09g092290.1.1	.	polypeptide	1	848	.	+	.	ID=Solyc09g092290.1.1;md5=29b4ad1c6ed49344553a6609ac4a2bfb
Solyc09g092290.1.1	CDD	protein_match	185	296	1.13223E-6	+	.	date=25-02-2022;Target=Solyc09g092290.1.1 185 296;ID=match$10_185_296;signature_desc=AAA;Name=cd00009;status=T
Solyc09g092290.1.1	SMART	protein_match	179	327	5.0E-6	+	.	date=25-02-2022;Target=Solyc09g092290.1.1 179 327;ID=match$11_179_327;Name=SM00382;status=T;Dbxref="InterPro:IPR003593"
##sequence-region NP_001117396 1 1161
NP_001117396	.	polypeptide	1	1161	.	+	.	ID=NP_001117396;md5=f5717209c6c07f078e89f71c2dbf1fbb
NP_001117396	SMART	protein_match	203	349	2.9E-5	+	.	date=25-02-2022;Target=NP_001117396 203 349;ID=match$12_203_349;Name=SM00382;status=T;Dbxref="InterPro:IPR003593"
##FASTA
>NP_001117396
..................................
============
Thanks for your reply

**Comment by Lsz-20** [comment]
I found that the 'test_interpro.gff3' in sample_data shows the ##interproscan-version 5.46-81.0.is different from the 5.53 you offered?Will there be problems here

**Comment by slt666666** [comment]
Sorry for the late reply.
What command did you use to generate empty output?
I tried to use Interproscan version5.53 & 5.54 for NLRtracker, and both versions generate no problems.
And the result of your Interproscan(ver5.54) is too short. 
Installation of your Interproscan might have some problems.

ex) several lines of correct output of ver5.54
##gff-version 3
##feature-ontology http://song.cvs.sourceforge.net/viewvc/song/ontology/sofa.obo?revision=1.269
##interproscan-version 5.54-87.0
##sequence-region NP_001325023 1 648
NP_001325023    .       polypeptide     1       648     .       +       .       ID=NP_001325023;md5=4a8b389e0adecef09333d5e5ae1fced9
NP_001325023    CDD     protein_match   67      298     3.28741E-93     +       .       date=10-03-2022;Target=NP_001325023 67 298;ID=match$1_67_298;signature_desc=ABCG_EPDR;Name=cd03213;status=T
NP_001325023    Pfam    protein_match   91      243     3.7E-23 +       .       date=10-03-2022;Target=NP_001325023 91 243;ID=match$2_91_243;signature_desc=ABC transporter;Name=PF00005;status=T;Dbxref="InterPro:IPR003439"
NP_001325023    SUPERFAMILY     protein_match   70      301     1.18E-43        +       .       date=10-03-2022;Target=NP_001325023 70 301;ID=match$3_70_301;Name=SSF52540;status=T;Dbxref="InterPro:IPR027417"
NP_001325023    SMART   protein_match   100     293     8.8E-13 +       .       date=10-03-2022;Target=NP_001325023 100 293;ID=match$4_100_293;Name=SM00382;status=T;Dbxref="InterPro:IPR003593"
NP_001325023    ProSiteProfiles protein_match   70      316     18.727617       +       .       date=10-03-2022;Target=NP_001325023 70 316;ID=match$5_70_316;signature_desc=ATP-binding cassette, ABC transporter-type domain profile.;Name=PS50893;status=T;Dbxref="InterPro:IPR003439"
NP_001325023    Pfam    protein_match   392     603     1.7E-43 +       .       date=10-03-2022;Target=NP_001325023 392 603;ID=match$6_392_603;signature_desc=ABC-2 type transporter;Name=PF01061;status=T;Dbxref="InterPro:IPR013525"
NP_001325023    Pfam    protein_match   273     335     9.9E-8  +       .       date=10-03-2022;Target=NP_001325023 273 335;ID=match$7_273_335;signature_desc=ABC-2 type transporter;Name=PF19055;status=T;Dbxref="InterPro:IPR043926"
NP_001325023    Gene3D  protein_match   64      303     9.1E-54 +       .       date=10-03-2022;Target=NP_001325023 64 303;ID=match$8_64_303;Name=G3DSA:3.40.50.300;status=T;Dbxref="InterPro:IPR027417"
##sequence-region Solyc09g098100.3.1 1 1279
Solyc09g098100.3.1      .       polypeptide     1       1279    .       +       .       ID=Solyc09g098100.3.1;md5=eda089c2fdec8a8b7bde85228b72ff60

I replace test_interpro.gff3 (by ver5.46-81.0) to test_interpro.gff3 (by ver5.53-87.0).
But it's not a problem. Output is almost the same.

**Comment by Lsz-20** [comment]
Thank you for your reply.I seem to have found the problem. the Interproscan i installed have some trouble, and i have tried 5.52 it can work well.
